version: '3.8'

services:
  php:
    build: .
    container_name: php
    working_dir: /var/www
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - .:/var/www
    networks:
      - saas_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - saas_net

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: saas
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - saas_net

networks:
  saas_net:

volumes:
  db_data:
